# These configs require `cargo +nightly fmt` to work.
unstable_features = true
edition = "2024"
style_edition = "2024"

newline_style = "Unix"

# We insist on vertical layout for several reasons:
# - it is a uniform style to read
# - it is the most diff-friendly style
fn_params_layout = "Vertical"

normalize_comments = true
format_macro_matchers = true

reorder_impl_items = true
use_field_init_shorthand = true

wrap_comments = true

format_code_in_doc_comments = true
doc_comment_code_block_width = 80

# Give a hint about deps in the grouping.
group_imports = "StdExternalCrate"
# We still get cargo grouping, but the vert style is more diff-friendly.
# Maximum diff-friendly would be "Item", but it is not as readable.
imports_granularity = "Crate"
# Again, using vertical layout for diff-friendlyness.
imports_layout = "Vertical"
